from dsmirai.global_dqn_agent import GlobalDQNAgent as dqn
import numpy as np


def get_smart_bw_value(state, rl_type='dqn'):
    action_size = 10
    epsilon = 0.0001
    state_size = 2
    print('State_size: {}'.format(state_size))
    print('Action_size: {}'.format(action_size))
    print('The received state is: {}'.format(state))
    agent = dqn(state_size, action_size, epsilon=epsilon)
    # Loading the Model's weights generated by the selected model
    # TODO: Need to copy the model in that folder to be able to re-load it.
    agent.load(rl_type)
    state = np.reshape(state, [1, state_size])
    action = agent.act(state)
    print('##########################################')
    print('##########################################')
    print('The selected action is: {}'.format(action))
    print('##########################################')
    print('##########################################')
    return action * 100
